### ISSUE TITLE
Choosing and Setting license for the project

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#12]
- [x] Choose specific license for the project
- [x] Set that license to the projects repository to meet github's recommended community standards

**Comment by davialvb** [comment]
I  choose MIT license because it's a permissive free software license. As a permissive license, it puts an only very limited restriction on reuse and has, therefore, excellent license compatibility. The MIT license permits reuse within proprietary software provided that all copies of the licensed software include a copy of the MIT License terms and the copyright notice. What do you think?

**Comment by thiagoiferreira** [comment]
License approved, recommended community standard met, closing issue.

**Comment by gabrielziegler3** [comment]
@all-contributors please add @davialvb for docs
